export const TOGGLE_CART = "TOGGLE_CART";
export const TOGGLE_USER_INFO = "TOGGLE_USER_INFO";
export const UPDATE_CART_ITEM_AMMOUNT = "UPDATE_CART_ITEM_AMMOUNT";
export const UPDATE_CART_EXTRA_AMMOUNT = "UPDATE_CART_EXTRA_AMMOUNT";