export const SET_USER_INFO_VISIBILITY = "SET_USER_INFO_VISIBILITY";
export const SET_CART_VISIBILITY = "SET_CART_VISIBILITY";
export const UPDATE_CART = "UPDATE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const DISPATCH_ORDER = "DISPATCH_ORDER";
export const SET_LOADING = "SET_LOADING";
export const SET_USER = "SET_USER";